os:
  - Visual Studio 2017

environment:
  matrix:
  - TOOLSET: vs2015
  - TOOLSET: vs2017

configuration:
  - Debug
  - Release

install:
  - git submodule update --init
  - bin\genie --sound %TOOLSET%

build:
  project: build/projects/$(TOOLSET)/mud.sln
