language: cpp

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.7
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.7
      - g++-5
      - gcc-5
      - xorg-dev
            
compiler:
  - gcc
  - clang

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5" COMPILER="gcc" GMAKE_FOLDER="gmake-linux"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7" COMPILER="clang" GMAKE_FOLDER="gmake-linux-clang"; fi

script:
  - mud/bin/genie --gcc=linux-$CC gmake
  - cd build/projects/$GMAKE_FOLDER
  - make config=debug64

os:
  - linux